name: i18n-tasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  i18n-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.9'
          bundler-cache: true
      - name: Run i18n-tasks health
        run: bundle exec i18n-tasks health
      - name: Run i18n-tasks missing
        run: bundle exec i18n-tasks missing
      - name: Run i18n-tasks unused
        run: bundle exec i18n-tasks unused
